### ISSUE TITLE
Decimals in summarize(dataset, function(variable)) ?

### ISSUE THREAD

**Issue by federicazoe** [mdogucu/stats67-su20-website#20]
For the quizzes, I would like to ask some questions to do in R.  

The command summarize  always prints the answer rounded with no decimal digit, on my RStudio. 
I guess it would behave similarly for other students. I saw your printed solutions have more, though.

How do we do so that we have a uniform number of decimals printed across all students?

**Comment by mdogucu** [comment]
When knitted tibble prints out 1 decimal. I asked students to round to 1 decimal point when providing the answer.
