### ISSUE TITLE
Noise with blackboard

### ISSUE THREAD

**Issue by federicazoe** [mdogucu/stats67-su20-website#22]
Mine, as I am going through the videos, I just wanted to let you know, in case you didn't realize, that there is a steady noise while the blackboard is in use (e.g. in [this video](https://uci.yuja.com/V/Video?v=1393741&node=5163023&a=1269794558&autoplay=1) from about min. 8:45)

**Comment by mdogucu** [comment]
It is just lack of a proper mic and currently unsolvable.
