### ISSUE TITLE
Attendance

### ISSUE THREAD

**Issue by federicazoe** [mdogucu/stats67-su20-website#23]
How would you like me to account for today's attendance? 
Should I find attendants in the register on Canvas and assign them their grade for this week's attendance?

**Comment by mdogucu** [comment]
Yes the attendance assignments have already been created on Canvas. You can just enter them.

**Comment by federicazoe** [comment]
Perfect, done it! I will keep the screenshots stored in an attendance folder on my laptop until the end of the class.
