### ISSUE TITLE
quizzes - solutions and feedbacks

### ISSUE THREAD

**Issue by federicazoe** [mdogucu/stats67-su20-website#31]
A video with the solutions to all of week 1 quiz questions may be very long and unlikely to be visualized.

Most questions have >90-95% students answering correctly.

1) Can I focus only on the questions on which many students (<=80% correct answers) struggled?

2) If yes, can we give a more detailed feedback for **all** auto-graded questions on Gradescope? Some just have an incorrect-correct rubric at the moment, with no explanation.

**Comment by mdogucu** [comment]
Yes that works. Thank you. Also when you post the videos for solutions, please send out a Canvas announcement.
