### ISSUE TITLE
Homework 2

### ISSUE THREAD

**Issue by federicazoe** [mdogucu/stats67-su20-website#33]
How much/what would you like my contribution to be for homework 2?

**Comment by mdogucu** [comment]
I added this on [Gradescope](https://www.gradescope.com/courses/150893/assignments/593738)

**Comment by federicazoe** [comment]
This format does not work for short answer questions:

<img width="524" alt="Screen Shot 2020-08-14 at 9 57 47 AM" src="https://user-images.githubusercontent.com/56598125/90227393-c2f88300-de14-11ea-84f1-5ce3988019d1.png">

From[ Gradescope's manual](https://help.gradescope.com/article/gm5cmcz19k-instructor-assignment-online): "_Make sure to put the answer field on a separate line, with no text before or after it_"

I changed it to

<img width="377" alt="Screen Shot 2020-08-14 at 10 03 59 AM" src="https://user-images.githubusercontent.com/56598125/90227840-7eb9b280-de15-11ea-8de3-725b45b55226.png">

**Comment by federicazoe** [comment]
I wrote the last two questions and linked Homework 2 to the respective assignment on Canvas.
