### ISSUE TITLE
Midterm

### ISSUE THREAD

**Issue by federicazoe** [mdogucu/stats67-su20-website#34]
How much/what would you like my contribution to be for the midterm?

**Comment by mdogucu** [comment]
I added the to the midterm on [Gradescope](https://www.gradescope.com/courses/150893/assignments/585499/outline/edit). Let me know if anything is not clear.

**Comment by federicazoe** [comment]
I remember the question about the sample size in the 4-second workout study was found a bit ambiguous in stats 7, because students found it be not clear if the study looked at 8 men and 8 women (so 16 people in total) or at 8 people (both men and women).

Do we want to make it less ambiguous it in the sentence of the study, writing

_Texas scientists recruited eight healthy young individuals_

instead of 

_Texas scientists recruited eight healthy young men and women_ ?

**Comment by federicazoe** [comment]
I remember the question about the sample size in the 4-second workout study was found a bit ambiguous in stats 7, because students found it to be not clear if the study looked at 8 men and 8 women (so 16 people in total) or at 8 people (both men and women).

Do we want to make it less ambiguous it in the sentence of the study, writing

_Texas scientists recruited eight healthy young individuals_

instead of 

_Texas scientists recruited eight healthy young men and women_ ?

**Comment by mdogucu** [comment]
I now published Week 3 materials. When you write the Q4 please make sure to add the r code to week 3 schedule.

Note that I had initially wrote Q6 for you but I had time to write it which left us with only a specific option for Q5. Can you please read the other questions I wrote to make sure they look OK? Also, when you are done feel free to close this issue. Then I can take one more round of eyes and set points.

**Comment by federicazoe** [comment]
I finished Q4 and Q5 and read the rest of the questions. Everything looks OK to me.
