### ISSUE TITLE
midterm review

### ISSUE THREAD

**Issue by mdogucu** [mdogucu/stats67-su20-website#35]
Federica would you be able to update this [midterm review](https://mdogucu.ics.uci.edu/teaching/stats67-fa19/midterm/midterm-review-key.pdf) and record a solutions video?

**Comment by mdogucu** [comment]
We can talk more during our meeting.

**Comment by federicazoe** [comment]
Yes, I can!

**Comment by mdogucu** [comment]
Thank you so much for doing this.
