### ISSUE TITLE
S for Binomial and Poisson

### ISSUE THREAD

**Issue by federicazoe** [mdogucu/stats67-su20-website#39]
I saw the slides [Discrete Random Variables Review](https://www.stats4cs.com/schedule/slide/slide-3-discrete-review.html#12) provide S = {0,1,2,...} for the Geometric distribution but not for the Binomial and the Poisson.

I thought it could be good to include S also for them. 

I can do it if you think it would be good.

**Comment by mdogucu** [comment]
Yes, please

**Comment by federicazoe** [comment]
I will!
