### ISSUE TITLE
unaccountably

### ISSUE THREAD

**Issue by federicazoe** [mdogucu/stats67-su20-website#40]
I noticed the slides [Continuous Random Variables](https://www.stats4cs.com/schedule/slide/slide-3-cont-rv.html#2) use the expression "unaccountably infinite" for the sample space of a continuous random variable. Is it what it was meant to be written or is it a typo for "uncountably infinite"?

**Comment by mdogucu** [comment]
Yes it is a typo, please fix if you can

**Comment by federicazoe** [comment]
I will!
