### ISSUE TITLE
Homework 3

### ISSUE THREAD

**Issue by federicazoe** [mdogucu/stats67-su20-website#46]
I finished to write questions and explanations for homework 3. 

After you give it a look and eventually adjust points given to the questions, I can create the assignment on Canvas and link it to Gradescope.

**Comment by mdogucu** [comment]
Scoring is done. Also, I have added one more question, the last question to help with next week.

**Comment by mdogucu** [comment]
On the website can you also change the time of the homework to 2 hours please? It is rather long.
