### ISSUE TITLE
Normality and Constant variance plots

### ISSUE THREAD

**Issue by federicazoe** [mdogucu/stats67-su20-website#51]
quiz-5-slr  asks to create the plots to verify Normality and Constant Variance, but I did not see where they learned that

**Comment by mdogucu** [comment]
I create the residual variable for them in the code. The rest is just thinking in ggplot(). I however made a note for normality in the quiz to say that they can use geom_histogram() or geom_density(). They had not seen geom_density() before.

**Comment by federicazoe** [comment]
Great! Sorry, I didn't realize the code to add the residuals had been provided in the .Rmd
